### PR TITLE
feat(gui): change project manage page layout

### PR DESCRIPTION
**Pull request by lonelyicer**
Before:
image

After:
image

### CODE REVIEW

**Comment by anatawa12** [comment]
Umm...
It's reasonable to rearrange to put `…` to the left but I feel `Select Repositories` button should be on the left

How do you think `Upgrade All` `Select Repositories` `…` order?

**Comment by lonelyicer** [comment]
> How do you think `Upgrade All` `Select Repositories` `…` order? or putting some divier (space) between `Select Repositories` and `…` with original order?

Putting ‘...’ to the far right of the layout is more intuitive to the user, because it means ‘more action’.
Other apps generally do the same.

**Comment by lonelyicer** [comment]
As for `Upgrade All` and `Select Repositories`, I think the order from left to right should be `Select Repositories` `Upgrade All`,  because the actions given in `...` are related to the VPM Package, and it would be more intuitive to put the buttons that are more functionally related together.
However, this is not the most important part, and perhaps their positions could be switched.

**Comment by anatawa12** [comment]
After discussing with Sayamame-beans and some other friends yesterday night, I decided to keep current UI for now.

Thank you for suggestion!

**Comment by Sayamame-beans** [comment]
Just a note...
Upgrade All button won't be displayed if there's nothing to update, so if we place it in the center or to the right, other buttons' position will change depending on whether there are some upgradable or not.

**Pull request closed without merging**
