### PR TITLE
feat(zh_hant): add localization

### PR DESCRIPTION
**Pull request by yelandiealma**

### CODE REVIEW

**Comment by anatawa12** [comment]
Thank you for adding localization for ALCOM!

Could you add changelog entry in `CHANGELOG-gui.md`?

In addition, I could not maintain Chinese localization so can you maintain zh_hant localization in the future?

**Comment by yelandiealma** [comment]
> In addition, I could not maintain Chinese localization so can you maintain zh_hant localization in the future?

Of course! It's my pleasure!

**Comment by anatawa12** [comment]
> Of course! It's my pleasure!

Thank you! I'll add a bit of code to ci and merge tomorrow!

**Comment by anatawa12** [comment]
Oh I found this PR is "allow edits from maintainers" disabled and came from organization so unable to enable.

So, could you add the following code to localization-updates.js in the `.github/scripts` folder like commit 2725a8e280cfbc0edb584ec3489d55f69bfcab66?

```js
		{
			id: 'zh_hant',
			discussionNumber: 855,
			replyId: 'DC_kwDOIza9ks4An6A8'
		},
```

**Comment by anatawa12** [comment]
Thank you!

**Comment by anatawa12** [comment]
Thank you for adding localization for ALCOM, @yelandiealma!

Please follow and use #1443 and #894 for future localization discussion.
GitHub Actions will automatically notice you about new missing / removed keys in english localization file in #1443

**Pull request merged**
