### PR TITLE
Added support for Flatpak version of Unity Hub

### PR DESCRIPTION
**Pull request by gizmo-ds**
This adds support for the Flatpak version of Unity Hub. It works fine with Unity Hub 3.9.1 (Flatpak).

image

### CODE REVIEW

**Comment by gizmo-ds** [comment]
I'm not sure if adding this checkbox under the Unity Hub Path is the best approach, but I couldn't think of a better way to handle it.

**Review by anatawa12 — CHANGES_REQUESTED** [review]
Thank you for creating code for support flatpak!

However, I don't like to use `flatpak` as the special value for flatpak support and I don't want to include special support with `flatpak` command, I want to support with adding  `/var/lib/flatpak/app/com.unity.UnityHub/current/active/files/extra/unityhub` as default unity hub search path list

**Comment by gizmo-ds** [comment]
> Thank you for creating code for support flatpak!
> 
> However, I don't like to use `flatpak` as the special value for flatpak support and I don't want to include special support with `flatpak` command, I want to support with adding `/var/lib/flatpak/app/com.unity.UnityHub/current/active/files/extra/unityhub` as default unity hub search path list as I said in #1332.
> 
> Is there any other reason to implement this way?

Thanks for the feedback! I understand the preference for directly executing the Unity Hub executable. However, doing so would bypass the advantages of the Flatpak sandbox environment. I believe there might be other ways to approach this while still retaining the benefits of the sandbox.

**Comment by anatawa12** [comment]
umm.... I thought `/var/lib/flatpak/app/com.unity.UnityHub/current/active/files/extra/unityhub` is wrapper executable.

**Pull request closed without merging**
