### PR TITLE
Add German localization.

### PR DESCRIPTION
**Pull request by JustBuddy**
Adding German localization to the GUI.

### CODE REVIEW

**Comment by JustBuddy** [comment]
This is not done yet, I will finish it shortly.

**Comment by JustBuddy** [comment]
Translation done, will go through it and apply polish.

**Comment by anatawa12** [comment]
Thank you for adding new language!

I'd like to add a new language to ALCOM (vrc-get-gui) but I can't maintain german since I could not understand.
So I need your help to maintain german.
Could you please help me to maintain german localization?

In addition, currently reorganizing localization key is in progress in #787 so it might took several days before merging this PR. Sorry.

**Comment by JustBuddy** [comment]
Sure, I can do that. 
Let me know whenever you are done with the localization keys and I will update the PR accordingly.

**Pull request closed without merging**
