### PR TITLE
chore: Move from heroicons to lucide-react

### PR DESCRIPTION
**Pull request by JustBuddy**
Fixes https://github.com/vrc-get/vrc-get/issues/1129

What do you think?
image
image

From my test, it is safe to uninstall the heroicons package.
Please do so if you end up using this, I am not sure if I did the uninstallation correctly.

### CODE REVIEW

**Comment by anatawa12** [comment]
Thank you for implementation!


It looks good in general but the star icon on the checkbox is less noticeable I think so could you increase stroke width of star icon on the favorite checkbox?

https://lucide.dev/guide/basics/stroke-width

> From my test, it is safe to uninstall the heroicons package.

I don't like to create another PR to remove the heroicons from package.json so could you remove it from package.json?

**Comment by JustBuddy** [comment]
> It looks good in general but the star icon on the checkbox is less noticeable I think so could you increase stroke width of star icon on the favorite checkbox?
> 
> https://lucide.dev/guide/basics/stroke-width

Sure, I'll look into that.

> I don't like to create another PR to remove the heroicons from package.json so could you remove it from package.json?  

Do I just remove it from package.json? That's all?

**Comment by JustBuddy** [comment]
That's how different widths look.
imageimageimage
default - **width 3** - width 4

I think 3 is best, 4 looks a bit odd.

**Comment by anatawa12** [comment]
> Do I just remove it from package.json? That's all?

I think we need to call npm install again to update package-lock.json also.

**Comment by JustBuddy** [comment]
done, should be good now.

**Review by anatawa12 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
